### ISSUE TITLE
Sidebar auto-closing too quickly

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#179] opened 2016-06-27 20:11 UTC
Feels like 5 seconds before it closes? @chrismore do you think 2 minutes to auto-close is good?

**Comment by chrismore** [comment] 2016-06-27 21:05
@fabiorios here's the timer settings:

#137 

2 minutes after CTA clicking OR 5 minutes without clicking anything.

Should not be 5 seconds unless you have something in your config to set it to 5 seconds.

**Comment by chrismore** [comment] 2016-06-27 21:13
I just checked and the 5 minute auto close without clicking the CTA works as designed. Checking the 2 minute after CTA clicked.

**Comment by chrismore** [comment] 2016-06-27 21:14
Checked the auto close after 2 minutes with clicking the CTA and it works too.

**Comment by chrismore** [comment] 2016-06-27 21:15
@fabiorios are you using the latest master? It looks like the XPI was built 5 hours ago, so that should be the latest too.

**Comment by fabiorios** [comment] 2016-06-27 21:16
Hmm? I'll try to replicate on another machine.

*Fabio Rios* | Firefox Product Marketing | frios@mozilla.com | IRC: frios

**Comment by FrancescoSTL** [comment] 2016-06-27 21:16
Ah.. Sorry @fabiorios, I didn't catch that the autoclose is set in the config file. That change happened while I was gone ;). Check the `"afterInteractionCloseTime"` and `"defaultSidebarCloseTime"` settings in your config.json

**Comment by fabiorios** [comment] 2016-06-28 17:16
I was able to replicate this on a fresh computer. Running Windows 10. Firefox 47.0.1.

Here are my steps:
- installed addon
- visited first run
- selected new user
- selected do good (applies to both)
- "no thanks" to account sign up
- x'd out of the data import panel (this panel doesn't have the issue)
- clicked lightbulb when notification appears
- panel opens and closes 5 seconds later

**Comment by chrismore** [comment] 2016-06-29 04:41
I actually saw something like this today, but it seemed to be on the 5th sidebar only. I am trying to replicate.

**Comment by chrismore** [comment] 2016-06-29 04:44
@fabiorios I tried the steps above and it doesn't happen to me. I wonder if this is a Windows issue and since we are launching on Windows, we need to do more testing on Windows.

@schalkneethling Are you able to test this on a Windows machine?

**Comment by schalkneethling** [comment] 2016-06-29 09:29
@chrismore Will take a look

**Comment by FrancescoSTL** [comment] 2016-06-29 16:48
@schalkneethling If you click the action button multiple times, multiple timers start, and when you open the sidebar again, those timers aren't thrown away so the sidebar ends up closing. Same thing happens when you complete a CTA multiple times.

**Comment by fabiorios** [comment] 2016-06-29 18:31
@FrancescoSTL for what it's worth, the first sidebar works fine. Once I close it and I get the ping for the second one, that's when it goes nuts.

It happens even when I don't click the action button.

I've ordered a Windows 7 and Windows 8 loaner, I'll try it there too.

**Closed** 2016-07-01 16:43 UTC
Labels: bug, in progress, p1
