### ISSUE TITLE
Funnelcake - not interacting with addon before closing FX removes the addon

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#254] opened 2016-07-06 17:28 UTC
I tried multiple times, and have narrowed it down to not engaging within the sidebar. Even if I click the notification and see the sidebar, as long as I don't click anything inside the sidebar and instead just x out of it. When I reopen fx the addon is gone. If I click a button within the sidebar, it's OK upon reopen.

Windows 10, using the latest funnelcake on 7/6

New user
Do it yourself or do good
opt out of account through "no thanks"
click notification/bulb, but don't click anything inside the sidebar
Close the sidebar
Close Firefox
Reopen using desktop icon
Addon is no longer present.

**Comment by fabiorios** [comment] 2016-07-06 17:36
Note, the addon still appears within my extensions

**Comment by FrancescoSTL** [comment] 2016-07-06 17:42
Being that the latest funnelcake doesn't modify nonUseDestroyTimer and that this timer is set to 3 weeks, it is likely that this line might be the culprit https://github.com/mozilla/all-aboard/blob/master/index.js#L760

Although I'm not certain. There are many places that we are calling .destroy() and .dispose() functions. The one that is definitely happening here is removal of the ActionButton icon.

**Comment by FrancescoSTL** [comment] 2016-07-06 17:45
Seems to be only one place that we are calling `allAboard.destroy()`, which I believe to be the reason this is happening, and that is within `destroy()`. Further leading me to believe that https://github.com/mozilla/all-aboard/blob/master/index.js#L760 might be the reason this is happening. Unless somehow `nonuseDestroyTime` is being set, it is unlikely that one of the timers fired.

**Comment by fabiorios** [comment] 2016-07-06 18:45
I'm having no luck getting the addon to stay within the value track. Even after engaging with the sidebar content, if I close and reopen Firefox, the addon is gone from the toolbar.

In the utility track, if I engage with the sidebar content, it stays.

**Comment by FrancescoSTL** [comment] 2016-07-06 18:54
@schalkneethling any idea what might be going on here?

**Comment by schalkneethling** [comment] 2016-07-06 19:01
So, this line:
https://github.com/mozilla/all-aboard/blob/master/index.js#L1081

Will add the icon to the chrome if the first step has been seen (no interaction required), and this line will add it, if the questions have been answered, but no sidebar has been seen:
https://github.com/mozilla/all-aboard/blob/master/index.js#L1101

**Comment by schalkneethling** [comment] 2016-07-06 19:02
Is anyone else with the funnelcake build seeing this?

**Comment by FrancescoSTL** [comment] 2016-07-06 19:08
@bniolet1 confirmed this via slack earlier

**Comment by FrancescoSTL** [comment] 2016-07-06 19:09
@fabiorios if you navigate back to firstrun after the addon is "destroyed," do the questions show up? Also, if you hit ctrl-shift-r on the newtab page, do the pagemods show?

**Comment by fabiorios** [comment] 2016-07-06 21:38
@FrancescoSTL 

Addon destroyed -> navigated to /firstrun and still got back to golden questions
Yes, hard refresh on the newtab page made the pagemods show up.

**Comment by bniolet1** [comment] 2016-07-06 21:40
Happens for me even if I engage with content on utility track. 

Steps to reproduce: 
New user (no profile). 
Install funnelcake
answer two questions, "no thanks" past accounts page
for utility track, interact with first content. get the badge. 
interact with second content. get the badge. 
---with messaging pane still open, close Firefox. ---
start firefox. Lightbulb gone.

**Comment by FrancescoSTL** [comment] 2016-07-06 23:10
I wasn't able to replicate either case with the new funnelcake @bniolet1 @fabiorios. Are you sure you are wiping both profiles before running?

**Comment by FrancescoSTL** [comment] 2016-07-06 23:17
Nevermind, I was able to replicate. Trying to see if I can grab some reliable steps

**Comment by FrancescoSTL** [comment] 2016-07-06 23:49
I was able to replicate with @fabiorios's steps, except if there is a desktop notification open, I had to dismiss it before I reopened Firefox or the addon wouldn't destroy itself as noted in this bug

**Comment by FrancescoSTL** [comment] 2016-07-06 23:50
@schalkneethling I'm punching out for the evening. Seeing as this is a p1 bug, I was wondering if you could take a look tomorrow. This seems to be a big hole, and I am unsure if it is caused by simpleStorage or not

**Comment by schalkneethling** [comment] 2016-07-07 10:34
TEST 1
----------
Machine: Windows 10 (VM)
Browser: Firefox Funnelcake

1. Uninstall all versions of Firefox
2. Install funnelcake
3. Launch Firefox once install completed.
4. Launches with two tabs - what's new and about:home

Experience never starts because a user is unlikely to navigate to firstrun.

**Comment by schalkneethling** [comment] 2016-07-07 11:30
TEST 2
----------
Machine: Windows 10 (VM)
Browser: Firefox Funnelcake

1. Firefox 44.0.2 already installed
2. Install funnelcake (upgrade)
3. Launch Firefox once install completed.
4. Launches with two tabs - what's new and about:home

Experience never starts because a user is unlikely to navigate to firstrun.

**Comment by schalkneethling** [comment] 2016-07-07 11:40
TEST 3
----------
Continuing on from the above
1. Navigate explicitly to https://www.mozilla.org/en-US/firefox/47.0/firstrun/
2. Answer questions
3. Click No thanks on FxA
4. Wait for notification
5. Click notification icon
6. Did not interact with sidebar
7. Close Firefox
8. Open Firefox
9. Lightbulb icon is present

**Comment by schalkneethling** [comment] 2016-07-07 11:58
TEST 4
-----------
Machine: Windows 7 (VM)
Browser: Firefox funnelcake

1. Delete all Mozilla folders under Local and Roaming
2. Install funnelcake
3. Launch Firefox after install
4. Get import dialog (this seems wrong to me, should it not be disabled?)
5. Choose to not import anything
6. Firstrun is shown, with golden questions
7. Answer questions
8. Decline FxA
9. newtab changes not applied
10. Receive notification
11. Click lightbulb
12. Did not interact with sidebar
13. Close Firefox
14. Lightbulb is missing :-/

**Comment by schalkneethling** [comment] 2016-07-07 12:42
I am unable to replicate the above using a locally built XPI that I install into Firefox but, I have a theory on what may be the cause, and will open a pull request for this change so we can test and confirm.

**Comment by fabiorios** [comment] 2016-07-07 16:39
I tried the above using v5-funnelcake and it works fine on Windows 7.
I tried the above using v5-funnelcake and **it doesn't work** on Windows 8.

**Comment by FrancescoSTL** [comment] 2016-07-07 17:39
Potential fix is merged and awaits testing with the next funnelcake build.

**Comment by FrancescoSTL** [comment] 2016-07-08 04:30
@schalkneethling submitted PR for review in #270

**Closed** 2016-07-08 12:55 UTC
Labels: bug, p1
